# Generated by Django 2.2.1 on 2019-11-18 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notifData',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
