# Generated by Django 2.2.1 on 2019-11-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20191118_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentData', models.TextField(blank=True, null=True)),
                ('postedOn', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='createpost',
            name='comments',
            field=models.ManyToManyField(null=True, to='account.Comments'),
        ),
    ]
